# Generated by Django 5.2.8 on 2025-11-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=32, unique=True)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('lead_stage', models.CharField(choices=[('New', 'New'), ('Prospecting', 'Prospecting'), ('Qualified', 'Qualified'), ('Order Booked', 'Order Booked'), ('Won', 'Won'), ('Closed-Won', 'Closed-Won'), ('Closed-Lost', 'Closed-Lost'), ('Lost', 'Lost')], max_length=32)),
                ('lead_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=16)),
                ('dealer', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('segment', models.CharField(blank=True, max_length=64)),
                ('kva', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('kva_range', models.CharField(blank=True, max_length=32)),
                ('owner', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('win_flag', models.BooleanField(default=False)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('followup_count', models.PositiveSmallIntegerField(default=0)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('fy', models.CharField(blank=True, max_length=8)),
                ('month', models.CharField(blank=True, max_length=8)),
                ('week', models.CharField(blank=True, max_length=8)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
