# Generated by Django 5.2.8 on 2025-11-15 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='area_office',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='dg_ownership',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='enquiry_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='events',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='finance_company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='finance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='pan_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='phase',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='pincode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_from',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_segment',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='tehsil',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='zone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='lead',
            name='kva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_stage',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='lead',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
