# Generated by Django 5.2.8 on 2025-11-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_address_lead_area_office_lead_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
