# Generated by Django 5.2.8 on 2025-11-21 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create_lead', 'Created Lead'), ('update_lead', 'Updated Lead'), ('delete_lead', 'Deleted Lead'), ('bulk_delete_leads', 'Bulk Deleted Leads'), ('upload_file', 'Uploaded File'), ('apply_filters', 'Applied Filters'), ('export_data', 'Exported Data'), ('view_page', 'Viewed Page')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='crm_activit_timesta_c65c99_idx'), models.Index(fields=['user', '-timestamp'], name='crm_activit_user_id_a6bf2d_idx'), models.Index(fields=['action'], name='crm_activit_action_ced24b_idx')],
            },
        ),
    ]
