# Generated by Django 5.2.8 on 2025-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='lead',
            name='owner',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-updated_at'], name='crm_lead_updated_91b7ee_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['enquiry_date'], name='crm_lead_enquiry_d2ac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['close_date'], name='crm_lead_close_d_a08d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_status'], name='crm_lead_lead_st_e07da5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['dealer'], name='crm_lead_dealer_df77da_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner'], name='crm_lead_owner_290915_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['state'], name='crm_lead_state_305bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['enquiry_id'], name='crm_lead_enquiry_a26da3_idx'),
        ),
    ]
