# Generated by Django 5.2.8 on 2025-12-08 11:10

from django.db import migrations, models


def migrate_leads_uploaded_on_to_source(apps, schema_editor):
    """Migrate data from leads_uploaded_on to source field"""
    Lead = apps.get_model('crm', 'Lead')
    for lead in Lead.objects.exclude(leads_uploaded_on__isnull=True).exclude(leads_uploaded_on=''):
        # Extract filename from "filename|timestamp" format
        upload_value = lead.leads_uploaded_on
        if '|' in upload_value:
            filename = upload_value.split('|')[0]
            lead.source = filename
        else:
            lead.source = upload_value
        lead.save(update_fields=['source'])


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert source back to leads_uploaded_on format"""
    Lead = apps.get_model('crm', 'Lead')
    from django.utils import timezone
    for lead in Lead.objects.exclude(source__isnull=True).exclude(source=''):
        if lead.source != 'manual':
            # Convert back to "filename|timestamp" format
            timestamp = lead.updated_at.isoformat() if lead.updated_at else timezone.now().isoformat()
            lead.leads_uploaded_on = f"{lead.source}|{timestamp}"
            lead.save(update_fields=['leads_uploaded_on'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_leads_uploaded_on'),
    ]

    operations = [
        # First, add source field if it doesn't exist with proper attributes
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, db_index=True, help_text="Source of lead: 'manual' for manually created, or filename for Excel uploads", max_length=128),
        ),
        # Migrate data
        migrations.RunPython(migrate_leads_uploaded_on_to_source, reverse_migration),
        # Remove old field and index
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_leads_u_4b92b3_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='leads_uploaded_on',
        ),
        # Ensure source has index
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='crm_lead_source_0cf4cf_idx'),
        ),
    ]
